-- -- Create orders table first since order_items references it
-- CREATE TABLE orders (
--                         id BIGINT AUTO_INCREMENT PRIMARY KEY,
--                         customer_id BIGINT NOT NULL,
--                         customer_name VARCHAR(255) ,
--                         waiter_id BIGINT,
--                         waiter_name VARCHAR(255),
--                         table_number INT,
--                         order_status ENUM('PLACED', 'ACCEPTED', 'PREPARING', 'READY', 'DELIVERED', 'CANCELLED') NOT NULL,
--                         order_time DATETIME NOT NULL,
--                         estimated_delivery_time DATETIME,
--                         completion_time DATETIME,
--                         total_amount DECIMAL(19, 2) NOT NULL,
--                         special_instructions TEXT,
--                         is_paid BOOLEAN DEFAULT FALSE NOT NULL
-- );
--
-- -- Create order_items table
-- CREATE TABLE order_items (
--                              id BIGINT AUTO_INCREMENT PRIMARY KEY,
--                              order_id BIGINT NOT NULL,
--                              menu_item_id BIGINT NOT NULL,
--                              menu_item_name VARCHAR(255) NOT NULL,
--                              menu_item_variant_id BIGINT,
--                              variant VARCHAR(100),
--                              size ENUM('SMALL', 'MEDIUM', 'LARGE', 'EXTRA_LARGE'),
--                              quantity INT NOT NULL,
--                              unit_price DECIMAL(19, 2) NOT NULL,
--                              sub_total DECIMAL(19, 2) NOT NULL,
--                              special_instructions TEXT,
--                              CONSTRAINT fk_order_items_order
--                                  FOREIGN KEY (order_id)
--                                      REFERENCES orders (id)
--                                      ON DELETE CASCADE
-- );
--
-- -- Create indexes for better performance
-- CREATE INDEX idx_orders_customer_id ON orders (customer_id);
-- CREATE INDEX idx_orders_order_status ON orders (order_status);
-- CREATE INDEX idx_orders_order_time ON orders (order_time);
-- CREATE INDEX idx_order_items_order_id ON order_items (order_id);