spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: discovery-server



## Actuator endpoints for health checks
#management:
#  endpoints:
#    web:
#      exposure:
#        include: *
#  endpoint:
#    health:
#      show-details: always