server:
  port: 8080

spring:
  main:
      web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true


      routes:

        - id: user-auth
          uri: lb:http://user-service
          predicates:
            - Path=/api/auth/**

        - id: user-customers
          uri: lb:http://user-service
          predicates:
            - Path=/api/customers/**


        - id: user-employees
          uri: lb:http://user-service
          predicates:
            - Path=/api/employees/**



        - id: menu-service
          uri: lb:http://menu-service
          predicates:
            - Path=/api/menu/**
#          filters:
#            - AuthenticationFilter


        - id: order-service
          uri: lb:http://order-service
          predicates:
            - Path=/api/orders/**

        - id: payment-service
          uri: lb:http://payment-service
          predicates:
            - Path=/api/payments/**