spring:
  profiles:
    active: native
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations

# Make sure logging is verbose enough to diagnose issues
logging:
  level:
    org.springframework.cloud.config: DEBUG
    org.springframework.boot: INFO

# Actuator endpoints for health checks
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
server:
  port: 8888